FROM python:3.5
WORKDIR /
ADD . /
RUN echo ‘nameserver 8.8.8.8’ >> /etc/resolve.conf && echo ‘nameserver 8.8.4.4’ >> /etc/resolve.conf’ \
	&& apt-get update \
    && pip3 install flask \
    && pip3 install flask_restful \
    && pip3 install flask_jsonpify \
    && pip3 install requests \

    && git clone https://github.com/ferryjul/projet-integrateur-5sdbd.git

ENTRYPOINT  cd projet-integrateur-5sdbd; git pull; python3 processingMS/processingMS.py; tail -f /dev/null