FROM node:slim
WORKDIR /
ADD . /
RUN apt-get update && apt-get install -y \
    nodejs \
    npm \
    git \
    python3 \
    python3-pip \
    && pip3 install flask \
    && pip3 install flask_restful \
    && pip3 install flask_jsonpify \

    && git clone https://github.com/ferryjul/projet-integrateur-5sdbd.git \

ENTRYPOINT  cd projet-integrateur-5sdbd; git pull; python3 orchestrateurMS/orchestrateurMS.py; tail -f /dev/null